name: osbridge-lcca
channels:
  - conda-forge
dependencies:
  - python=3.10
  - flask
  - pyqt
  - plotly
  - pylatex
  - numpy
  - pandas
  - matplotlib
  - requests
  - pytest
  - pytest-qt
  - pip
  - pip:
      - -r requirements.txt
